---
- hosts: web
  tasks:
   - name: create file if doesnt exit
     file:
      state: touch
      path: /home/ansible/hostname.conf
   - name: If line not there then add it
     lineinfile:
        state: present
        dest: /home/ansible/hostname.conf
        line: Hostname={{ ansible_hostname }}
