---
- hosts: web
  become: yes
  tasks:
   - name: Install apache
     yum:
      name: httpd
      state: latest

   - name: create file if doesnt exit
     file:
      state: touch
      path: /var/www/html/index.html
   - name: If line not there then add it
     lineinfile:
        state: present
        dest: /var/www/html/index.html
        line: Hostname={{ ansible_hostname }}
   - name: restart apache
     service:
        name: httpd
        state: reloaded
        enabled: yes
