---
- hosts: web
  tasks:
       - shell: cat /etc/motd
         register: motd_contents
       - debug: msg="stdout={{ motd_contents }}"
       - debug: msg="MOTD os EMPTY"
         when: motd_contents.stdout == ""
