---
- hosts: web
  tasks:
    - name: Install mysql server
      yum: name=mysql-server state=latest
      ignore_errors: yes
      register: there
    - name: start mysql if there
      service: name=mysqld state=restart
      register: running
